# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 12:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('scene_name', models.CharField(max_length=250)),
                ('action', models.CharField(max_length=5000)),
                ('phrase', models.CharField(blank=True, max_length=5000)),
                ('response', models.CharField(blank=True, max_length=5000)),
                ('finished', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('display_name', models.CharField(default='', max_length=50)),
                ('known', models.BooleanField(default=False)),
                ('flavour', models.CharField(blank=True, default='', max_length=250)),
                ('experience', models.IntegerField(default=0)),
                ('levelup', models.BooleanField(default=False)),
                ('pause', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CharParm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('flavour', models.CharField(max_length=2000)),
                ('value', models.IntegerField()),
                ('override_cost', models.IntegerField(default=-1)),
                ('affected_by', models.ManyToManyField(to='game.CharParm')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('flavour', models.CharField(max_length=250)),
                ('invite', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Influence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('visible', models.BooleanField()),
                ('affects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.CharParm')),
            ],
        ),
        migrations.CreateModel(
            name='InfSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=250)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('flavour', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Character')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.InfSet')),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ParmGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('flavour', models.CharField(blank=True, max_length=2000)),
                ('cost_to_add', models.IntegerField(default=40)),
                ('cost', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('parm_name', models.CharField(max_length=250)),
                ('base_dice', models.IntegerField(default=100)),
                ('dice_roll', models.IntegerField(default=0)),
                ('parm_bonus', models.IntegerField(default=0)),
                ('free_bonus', models.IntegerField(default=0)),
                ('difficulty', models.IntegerField(default=0)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Action')),
                ('char', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Character')),
                ('parm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.CharParm')),
            ],
        ),
        migrations.CreateModel(
            name='RollVisibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_dice_roll', models.BooleanField()),
                ('visible_parm_bonus', models.BooleanField()),
                ('visible_free_bonus', models.BooleanField()),
                ('visible_difficulty', models.BooleanField()),
                ('visible_result', models.BooleanField()),
                ('visible_passed', models.BooleanField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Players')),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Roll')),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('flavour', models.CharField(max_length=2000)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('flavour', models.CharField(max_length=250)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('turns', models.IntegerField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Character')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.InfSet')),
            ],
        ),
        migrations.AddField(
            model_name='parmgroup',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Setting'),
        ),
        migrations.AddField(
            model_name='languages',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Setting'),
        ),
        migrations.AddField(
            model_name='influence',
            name='infset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.InfSet'),
        ),
        migrations.AddField(
            model_name='game',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Setting'),
        ),
        migrations.AddField(
            model_name='charparm',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.ParmGroup'),
        ),
        migrations.AddField(
            model_name='character',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game'),
        ),
        migrations.AddField(
            model_name='character',
            name='languages',
            field=models.ManyToManyField(to='game.Languages'),
        ),
        migrations.AddField(
            model_name='character',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='character',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Scene'),
        ),
        migrations.AddField(
            model_name='action',
            name='char',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Character'),
        ),
        migrations.AddField(
            model_name='action',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game'),
        ),
        migrations.AddField(
            model_name='action',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Languages'),
        ),
        migrations.AddField(
            model_name='action',
            name='scene',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Scene'),
        ),
    ]
