# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charparm',
            old_name='affeced_by',
            new_name='affected_by',
        ),
    ]
