# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='flavour',
            field=models.CharField(default='flavour', max_length=50),
            preserve_default=False,
        ),
    ]
