# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='display_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='flavour',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='character',
            name='languages',
            field=models.ManyToManyField(null=True, to='game.Languages'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
