# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20171002_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Setting')),
            ],
        ),
        migrations.AlterField(
            model_name='players',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
