# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20171019_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollvisibility',
            name='visible_dice_roll',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rollvisibility',
            name='visible_difficulty',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rollvisibility',
            name='visible_free_bonus',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rollvisibility',
            name='visible_parm_bonus',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rollvisibility',
            name='visible_passed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rollvisibility',
            name='visible_result',
            field=models.BooleanField(default=True),
        ),
    ]
