# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_item_flavour'),
    ]

    operations = [
        migrations.AddField(
            model_name='infset',
            name='character',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.Character'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infset',
            name='reference',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='item',
            name='flavour',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
