# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20171019_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rollvisibility',
            old_name='visible_free_bonus',
            new_name='visible_bonus',
        ),
        migrations.RemoveField(
            model_name='rollvisibility',
            name='visible_parm_bonus',
        ),
    ]
