# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20171023_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='ambiance',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
