# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20171014_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='name',
            field=models.CharField(default='name', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
