# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20171014_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='visible',
        ),
        migrations.AddField(
            model_name='infset',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
