# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_scene_ambiance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='ambiance',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
