# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20171014_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infset',
            name='visible',
        ),
    ]
