# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_infset_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=5000)),
                ('phrase', models.CharField(max_length=5000)),
                ('response', models.CharField(max_length=5000)),
                ('finished', models.BooleanField(default=False)),
                ('char', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Character')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Languages')),
            ],
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parm', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('PASS', 'Сложность'), ('SURPASS', 'Больше на __')], default='PASS', max_length=15)),
                ('dice', models.IntegerField(default=0)),
                ('parm_bonus', models.IntegerField(default=0)),
                ('free_bonus', models.IntegerField(default=0)),
                ('difficulty', models.IntegerField(default=0)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Action')),
            ],
        ),
        migrations.CreateModel(
            name='RollVisibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_dice', models.BooleanField()),
                ('visible_parm_bonus', models.BooleanField()),
                ('visible_free_bonus', models.BooleanField()),
                ('visible_difficulty', models.BooleanField()),
                ('visible_result', models.BooleanField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Players')),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Roll')),
            ],
        ),
        migrations.AddField(
            model_name='influence',
            name='visible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
