# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20171016_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.InfSet'),
        ),
        migrations.AlterField(
            model_name='status',
            name='turns',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
