# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20171016_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='scene',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Scene'),
        ),
        migrations.AddField(
            model_name='action',
            name='scene_name',
            field=models.CharField(default='lol', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roll',
            name='parm_name',
            field=models.CharField(default='lol', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Scene'),
        ),
        migrations.AlterField(
            model_name='roll',
            name='parm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.CharParm'),
        ),
    ]
